# Generated by Django 2.2.6 on 2019-10-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20191022_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='lessons',
            new_name='lesson',
        ),
    ]
